//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotlineLog
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<System.DateTime> DateOfCall { get; set; }
        public string Operator { get; set; }
        public string FTEStatus { get; set; }
        public string ClearedToWork { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastDayWorked { get; set; }
        public Nullable<System.DateTime> ReturnToWorkDt { get; set; }
        public string STDElection_2020 { get; set; }
        public string RateOfPay { get; set; }
        public string HoursPreviouslyPaid { get; set; }
        public Nullable<System.DateTime> PayPeriodPayDate { get; set; }
        public string FTEHours { get; set; }
        public string DiffHoursToFTE { get; set; }
        public Nullable<int> RawDataNo { get; set; }
        public string NotesFromBenefits { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string Modifiedby { get; set; }
        public bool isActive { get; set; }
        public string STDElection_2021 { get; set; }
        public string RecordStatus { get; set; }
        public string PayReviewStatus { get; set; }
        public string STDElection_ThisYear { get; set; }
        public string STDElection_PrevYear { get; set; }
    }
}
