//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDecision
    {
        public int ID { get; set; }
        public int HotlineLogID { get; set; }
        public string EmployeeID { get; set; }
        public string PayDecisionStatus { get; set; }
        public string ClockedIn_ClearedToWork_Dt { get; set; }
        public Nullable<System.DateTime> STDPayDtTo { get; set; }
        public Nullable<System.DateTime> STDPayDtFrom { get; set; }
        public string STDPayHours { get; set; }
        public Nullable<System.DateTime> PayDecisionDt { get; set; }
        public string STDHoursPaidByNSHGross { get; set; }
        public string PTOAdjustment { get; set; }
        public string ReverseRegHours { get; set; }
        public string Notes { get; set; }
        public string SentToCigna { get; set; }
        public string STDPayDates { get; set; }
        public Nullable<int> HotLineLogPayDecisionTempID { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string ModifiedBy { get; set; }
        public bool isActive { get; set; }
        public bool ReturnToWork { get; set; }
        public string HoursInTimeCard { get; set; }
        public bool MadeWhole { get; set; }
        public string COVIDBankPayGross { get; set; }
        public Nullable<bool> Week1Cigna { get; set; }
        public Nullable<bool> Week2Cigna { get; set; }
        public string Week1TimeCardHours { get; set; }
        public string Week2TimeCardHours { get; set; }
        public string Week1COVIDPayHours { get; set; }
        public string Week2COVIDPayHours { get; set; }
        public string Week1COVIDPayGross { get; set; }
        public string Week2COVIDPayGross { get; set; }
        public string COVIDPayTotalGross { get; set; }
        public string PTOHoursPaid { get; set; }
        public string PTODollarsPaid { get; set; }
        public string PTOHoursPaidWeek1 { get; set; }
        public string PTODollarsPaidWeek1 { get; set; }
        public string PTOHoursPaidWeek2 { get; set; }
        public string PTODollarsPaidWeek2 { get; set; }
        public string PTOPayHours { get; set; }
        public string PTOAddedByTimekeeper { get; set; }
        public string TotalPTOAdjustment { get; set; }
        public string COVIDTestPTOAdjustment { get; set; }
    }
}
