//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotLineLogEntities : DbContext
    {
        public HotLineLogEntities()
            : base("name=HotLineLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<EmployeeMerit> EmployeeMerits { get; set; }
        public virtual DbSet<PayDecision> PayDecisions { get; set; }
        public virtual DbSet<CovidCases> CovidCases { get; set; }
        public virtual DbSet<PayDecisionDate> PayDecisionDates { get; set; }
        public virtual DbSet<EmployeeSTDElection> EmployeeSTDElections { get; set; }
        public virtual DbSet<HotlineLog> HotlineLogs { get; set; }
    }
}
