//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSTDElection
    {
        public string EmployeeID { get; set; }
        public string TotalSTDElectionPrevYear { get; set; }
        public string TotalSTDElectionThisYear { get; set; }
    }
}
