//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CovidTest
    {
        public string ACCESSIONNUMBER { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public Nullable<System.DateTime> RESULTED { get; set; }
        public string RESULT { get; set; }
        public int ID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
    }
}
