//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMerit
    {
        public string EmployeeID { get; set; }
        public Nullable<decimal> HourlyPayRate { get; set; }
        public string EmployeeFirstName { get; set; }
        public Nullable<decimal> CombinedFTEStatus { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeName { get; set; }
    }
}
