//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidPayTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSTDElection
    {
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string SSN { get; set; }
        public string Status { get; set; }
        public string StructureGroup { get; set; }
        public string STDElection { get; set; }
        public string STDElectionPercent { get; set; }
        public string STDReview { get; set; }
        public Nullable<System.DateTime> STDEffectiveDt { get; set; }
        public string STD2Election { get; set; }
        public string STD2ElectionPercent { get; set; }
        public string TotalSTDElectionPercent { get; set; }
        public string BenefitStatus { get; set; }
        public string TotalSTDElection2020 { get; set; }
        public string TotalSTDElection2021 { get; set; }
        public string TotalSTDElectionPrevYear { get; set; }
        public string TotalSTDElectionThisYear { get; set; }
    }
}
